# Generated by Django 3.2 on 2021-04-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210428_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_expired',
            field=models.DateTimeField(),
        ),
    ]
