# Generated by Django 3.2 on 2021-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_expired',
            field=models.DateField(),
        ),
    ]
