# Generated by Django 3.2 on 2021-04-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_date_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_room',
            new_name='document_root',
        ),
    ]
