# Generated by Django 3.2 on 2021-04-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
