# Generated by Django 3.2 on 2021-05-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210505_1315'),
        ('major', '0003_education_warcraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='accounts.dossier'),
        ),
    ]
