# Generated by Django 3.2 on 2021-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0004_alter_education_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warcraft',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
